definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  foundrykit:
    name: FoundryKit Workflow
    instance_type: mac_mini_m2
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "FoundryKit"
        APP_ID: "FoundryKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
          - 'Examples'
          - 'Package.swift'
    triggering:
      <<: *events
    scripts:
      - name: Build Swift Package
        script: |
          swift build
    artifacts:
      - build/**/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
