definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  foundrykit:
    name: FoundryKit Workflow
    instance_type: mac_mini_m2
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "FoundryKit"
        APP_ID: "FoundryKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
          - 'Examples'
          - 'Package.swift'
    triggering:
      <<: *events
    scripts:
      - name: Install dependencies
        script: |
          brew install xcodegen
      
      - name: Build Swift Package
        script: |
          swift build
      
      - name: Generate Example App Project
        script: |
          cd Examples/FoundryMacroExample
          xcodegen generate
      
      - name: Build Example App (iOS)
        script: |
          cd Examples/FoundryMacroExample
          xcodebuild -scheme FoundryMacroExample \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            -configuration Debug \
            build
    
    artifacts:
      - build/**/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
