name: FoundryMacroExample
options:
  bundleIdPrefix: com.foundrykit
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"

targets:
  FoundryMacroExample:
    type: application
    platform: [iOS, macOS]
    sources:
      - FoundryMacroExample
    dependencies:
      - package: FoundryKit
        product: FoundryKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foundrykit.macroexample
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: 6.2
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_EMIT_LOC_STRINGS: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Foundry Macro Example"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          ENABLE_PREVIEWS: YES
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          ENABLE_PREVIEWS: NO

packages:
  FoundryKit:
    path: ../..
