name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-build-test:
    name: Swift Build & Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Swift Build
      run: swift build
    
    - name: Swift Test
      run: swift test

  example-app-build:
    name: Build Example App
    runs-on: macos-latest
    needs: swift-build-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Install XcodeGen
      run: brew install xcodegen
    
    - name: Generate Xcode Project
      run: |
        cd Examples/FoundryMacroExample
        xcodegen generate
    
    - name: Build Example App (iOS)
      run: |
        cd Examples/FoundryMacroExample
        xcodebuild -scheme FoundryMacroExample_iOS \
          -destination "platform=iOS Simulator,name=iPhone 16" \
          -configuration Debug \
          build
    
    - name: Build Example App (macOS)
      run: |
        cd Examples/FoundryMacroExample
        xcodebuild -scheme FoundryMacroExample_macOS \
          -destination "platform=macOS" \
          -configuration Debug \
          build